name: Deploy React App with Terraform

on:
  push:
    branches:
      - feature/reactproject
      - main

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: mui-react-sample
        run: npm install

      - name: Build React app
        working-directory: mui-react-sample
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::774515140395:role/github-oidc-role
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        working-directory: terraform_aws
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform_aws
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform_aws
        run: terraform apply -auto-approve

      - name: Upload build to S3
        run: |
          aws s3 sync mui-react-sample/dist s3://${{ vars.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    needs: deploy-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: mui-react-sample
        run: npm install

      - name: Build React app
        working-directory: mui-react-sample
        run: npm run build