name: Deploy React App with Terraform

on:
  push:
    branches:
      - feature/reactproject

permissions:
  id-token: write
  contents: read

jobs:

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: mui-react-sample
        run: npm install

      - name: Build React app
        working-directory: mui-react-sample
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::774515140395:role/github-oidc-role
          aws-region: ap-south-1

      - name: Upload build to S3
        run: |
          aws s3 sync mui-react-sample/dist s3://${{ vars.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Trigger Terraform Repo
        run: |
          curl -i -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ vars.TERRAFORM_REPO_TOKEN }}" \
          https://api.github.com/repos/https://github.com/Udayreddy8339/Terraform_Project/dispatches \
          -d '{"event_type":"react-updated"}'
      - name: Debug Token Access
        run: |
          curl -i \
          -H "Authorization: Bearer ${{ secrets.TERRAFORM_REPO_TOKEN }}" \
          https://api.github.com/user